apiVersion: v1
kind: Namespace
metadata:
  name: todoapp

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dbconfig
  namespace: todoapp
data:
  MYSQL_HOST: svctododb.todoapp.svc.cluster.local 
  MYSQL_USER: root 
  MYSQL_PASSWORD: P@ssword
  MYSQL_DATABASE: tododb

---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  namespace: todoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapi  # Ensure this matches the labels in the template
  template:
    metadata:
      labels:
        app: todoapi  # Ensure this matches the selector labels
    spec:
      containers:
        - name: todo-app-container
          image: sumeetkumarnaik/todoapp:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  namespace: todoapp
spec:
  selector:
    app: todoapi
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: svctododb
  namespace: todoapp
spec:
  type: ClusterIP
  selector:
    app: mysqldb
  ports:
    - port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: svctodoapp
  namespace: todoapp
spec:
  type: LoadBalancer
  selector:
    app: todoapi
  ports:
    - port: 80
      targetPort: 80

--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydbpv
  namespace: todoapp
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: /tmp/mysql
    type: DirectoryOrCreate

--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydbpvc
  namespace: todoapp
spec:
  storageClassName: slow
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  namespace: todoapp
spec:
  replicas: 1  # Assuming you want only one replica for the database
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      nodeSelector:
        gpu: nvidia
      containers:
      - name: mysqldb
        image: mysql
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: dbconfig
                key: MYSQL_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: dbconfig
                key: MYSQL_DATABASE
        volumeMounts:
        - name: dbpath
          mountPath: /var/lib/mysql
      volumes:
      - name: dbpath
        persistentVolumeClaim:
          claimName: mydbpvc

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  namespace: todoapp
spec:
  replicas: 2  # Assuming you want two replicas for the application
  selector:
    matchLabels:
      app: todoapi
  template:
    metadata:
      labels:
        app: todoapi
    spec:
      nodeSelector:
        gpu: nvidia
      containers:
      - name: todoapi
        image: sumeetkumarnaik/todoapimysql:1.0
        ports:
          - containerPort: 80
        env:
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: dbconfig
                key: MYSQL_HOST
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: dbconfig
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: dbconfig
                key: MYSQL_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: dbconfig
                key: MYSQL_DATABASE
