apiVersion: v1
kind: Namespace
metadata:
  name: mysql-namespace

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: mysql-namespace
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storage-class
  hostPath:
    path: /path/to/host/directory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: mysql-namespace
spec:
  storageClassName: mysql-storage-class
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mysql-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: dbpath
              mountPath: /var/lib/mysql

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql-namespace
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql-namespace
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==  # base64-encoded "root"
  MYSQL_HOST: c3ZjdG9kb2RiLnRvZG9hcHAuc3ZjLmNsdXN0ZXIubG9jYWwgCg==  # base64-encoded "svctododb.todoapp.svc.cluster.local"
  MYSQL_USER: cm9vdA==  # base64-encoded "root"
  MYSQL_PASSWORD: UEBzc3dvcmQ=  # base64-encoded "P@ssword"
  MYSQL_DATABASE: dG9kb2Ri  # base64-encoded "tododb"
